# Generated by Django 5.1.2 on 2024-10-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hrid', models.CharField(max_length=100)),
                ('FullName', models.CharField(max_length=100)),
                ('LocationDesc', models.CharField(max_length=100)),
                ('Team', models.CharField(max_length=100)),
                ('DateRegistered', models.DateTimeField()),
            ],
        ),
    ]
