# Generated by Django 5.1.2 on 2024-10-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0002_delete_team_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Access',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_region', models.CharField(max_length=10)),
                ('project_id', models.CharField(max_length=100)),
                ('project_site', models.CharField(max_length=100, null=True)),
                ('project_description', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=250)),
                ('updated_by', models.CharField(max_length=250)),
            ],
        ),
    ]
