# Generated by Django 5.1.2 on 2024-11-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('HRID', models.CharField(max_length=10)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100, null=True)),
                ('MiddleName', models.CharField(max_length=100)),
                ('Role', models.CharField(max_length=1)),
                ('BuildingAssignment', models.CharField(max_length=20)),
                ('SamAccount', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=20)),
                ('Team', models.CharField(max_length=20)),
                ('LineofBusiness', models.CharField(max_length=20)),
                ('IsActive', models.BooleanField(default=True)),
                ('Date_Created', models.DateTimeField(auto_now_add=True)),
                ('Date_Updated', models.DateTimeField(auto_now=True)),
                ('Created_by', models.CharField(max_length=250)),
                ('Cpdated_by', models.CharField(max_length=250)),
            ],
        ),
    ]
