# Generated by Django 5.1.2 on 2024-11-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_user_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_admin',
            old_name='Cpdated_by',
            new_name='Updated_by',
        ),
        migrations.AlterField(
            model_name='user_admin',
            name='Email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_admin',
            name='LineofBusiness',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_admin',
            name='Team',
            field=models.CharField(max_length=100),
        ),
    ]
