# Generated by Django 5.1.2 on 2024-11-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropDownLookup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('category_id', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=150)),
                ('updated_by', models.CharField(max_length=150)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
