# Generated by Django 5.1.2 on 2024-11-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_agentcts'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcts',
            name='projectId',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
