# Generated by Django 5.1.2 on 2025-01-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_agentcts_projectid'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcts',
            name='support_callback_type',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='agentcts',
            name='support_created_by',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='agentcts',
            name='support_dispatch_call_equipment',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='agentcts',
            name='support_due_date',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='agentcts',
            name='support_notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='agentcts',
            name='support_reason_for_account_review',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='agentcts',
            name='support_resolved',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='agentcts',
            name='support_time',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='agentcts',
            name='support_transfer',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='agentcts',
            name='support_updated_by',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='agentcts',
            name='support_validated',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
